"""diary

Revision ID: 2118a21acd7e
Revises: 689d61b3fb2a
Create Date: 2021-04-08 12:02:18.101937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2118a21acd7e'
down_revision = '689d61b3fb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('poster_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'poster_path')
    # ### end Alembic commands ###
