"""empty message

Revision ID: 2c6cd95dcaf7
Revises: f939aa33a78e
Create Date: 2021-03-30 16:47:35.036383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6cd95dcaf7'
down_revision = 'f939aa33a78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('adventure', sa.Integer(), nullable=True),
    sa.Column('animation', sa.Integer(), nullable=True),
    sa.Column('comedy', sa.Integer(), nullable=True),
    sa.Column('crime', sa.Integer(), nullable=True),
    sa.Column('documentary', sa.Integer(), nullable=True),
    sa.Column('drama', sa.Integer(), nullable=True),
    sa.Column('family', sa.Integer(), nullable=True),
    sa.Column('fantasy', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('horror', sa.Integer(), nullable=True),
    sa.Column('music', sa.Integer(), nullable=True),
    sa.Column('mystery', sa.Integer(), nullable=True),
    sa.Column('romance', sa.Integer(), nullable=True),
    sa.Column('scifi', sa.Integer(), nullable=True),
    sa.Column('thriller', sa.Integer(), nullable=True),
    sa.Column('war', sa.Integer(), nullable=True),
    sa.Column('western', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_rating')
    # ### end Alembic commands ###
