"""genre ratings

Revision ID: 4fe15b2c113f
Revises: 91be7e039ed2
Create Date: 2021-03-30 15:59:56.844441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe15b2c113f'
down_revision = '91be7e039ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre__rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('adventure', sa.Integer(), nullable=True),
    sa.Column('animation', sa.Integer(), nullable=True),
    sa.Column('comdedy', sa.Integer(), nullable=True),
    sa.Column('crime', sa.Integer(), nullable=True),
    sa.Column('documentary', sa.Integer(), nullable=True),
    sa.Column('drama', sa.Integer(), nullable=True),
    sa.Column('family', sa.Integer(), nullable=True),
    sa.Column('fantasy', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('horror', sa.Integer(), nullable=True),
    sa.Column('music', sa.Integer(), nullable=True),
    sa.Column('mystery', sa.Integer(), nullable=True),
    sa.Column('romance', sa.Integer(), nullable=True),
    sa.Column('scifi', sa.Integer(), nullable=True),
    sa.Column('thriller', sa.Integer(), nullable=True),
    sa.Column('war', sa.Integer(), nullable=True),
    sa.Column('western', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('genre_ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_ratings',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.INTEGER(), nullable=True),
    sa.Column('adventure', sa.INTEGER(), nullable=True),
    sa.Column('animation', sa.INTEGER(), nullable=True),
    sa.Column('comedy', sa.INTEGER(), nullable=True),
    sa.Column('crime', sa.INTEGER(), nullable=True),
    sa.Column('documentary', sa.INTEGER(), nullable=True),
    sa.Column('drama', sa.INTEGER(), nullable=True),
    sa.Column('family', sa.INTEGER(), nullable=True),
    sa.Column('fantasy', sa.INTEGER(), nullable=True),
    sa.Column('history', sa.INTEGER(), nullable=True),
    sa.Column('horror', sa.INTEGER(), nullable=True),
    sa.Column('music', sa.INTEGER(), nullable=True),
    sa.Column('mystery', sa.INTEGER(), nullable=True),
    sa.Column('romance', sa.INTEGER(), nullable=True),
    sa.Column('sci-fi', sa.INTEGER(), nullable=True),
    sa.Column('thriller', sa.INTEGER(), nullable=True),
    sa.Column('war', sa.INTEGER(), nullable=True),
    sa.Column('western', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('genre__rating')
    # ### end Alembic commands ###
