"""users table

Revision ID: 6d7a1e4ec61c
Revises: 
Create Date: 2021-04-11 13:20:14.932327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7a1e4ec61c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=23), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_watched', sa.String(length=140), nullable=True),
    sa.Column('movie_name', sa.String(length=200), nullable=True),
    sa.Column('movie_id', sa.String(length=200), nullable=True),
    sa.Column('poster_path', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.String(length=140), nullable=True),
    sa.Column('user_rating', sa.String(length=140), nullable=True),
    sa.Column('rewatch', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('review', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('genre_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('adventure', sa.Integer(), nullable=True),
    sa.Column('animation', sa.Integer(), nullable=True),
    sa.Column('comedy', sa.Integer(), nullable=True),
    sa.Column('crime', sa.Integer(), nullable=True),
    sa.Column('documentary', sa.Integer(), nullable=True),
    sa.Column('drama', sa.Integer(), nullable=True),
    sa.Column('family', sa.Integer(), nullable=True),
    sa.Column('fantasy', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('horror', sa.Integer(), nullable=True),
    sa.Column('music', sa.Integer(), nullable=True),
    sa.Column('mystery', sa.Integer(), nullable=True),
    sa.Column('romance', sa.Integer(), nullable=True),
    sa.Column('scifi', sa.Integer(), nullable=True),
    sa.Column('thriller', sa.Integer(), nullable=True),
    sa.Column('war', sa.Integer(), nullable=True),
    sa.Column('western', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_rating')
    op.drop_table('followers')
    op.drop_table('diary')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
