"""diary

Revision ID: 760f4c19e756
Revises: 98e2c74d6698
Create Date: 2021-04-08 11:24:52.651630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760f4c19e756'
down_revision = '98e2c74d6698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('movie_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'movie_id')
    # ### end Alembic commands ###
