"""diary

Revision ID: 98e2c74d6698
Revises: 2c6cd95dcaf7
Create Date: 2021-04-07 15:17:54.965208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e2c74d6698'
down_revision = '2c6cd95dcaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_watched', sa.String(length=140), nullable=True),
    sa.Column('movie_name', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('rewatch', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('review', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary')
    # ### end Alembic commands ###
