"""diary table

Revision ID: a71e0437af0e
Revises: 69c6ae3cd9a3
Create Date: 2021-03-18 16:12:28.397129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71e0437af0e'
down_revision = '69c6ae3cd9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_watched', sa.DateTime(), nullable=True),
    sa.Column('movie_name', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('rewatch', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('review', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary')
    # ### end Alembic commands ###
