"""genre ratings

Revision ID: f939aa33a78e
Revises: 4fe15b2c113f
Create Date: 2021-03-30 16:08:59.325108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f939aa33a78e'
down_revision = '4fe15b2c113f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre__rating', sa.Column('comedy', sa.Integer(), nullable=True))
    op.drop_column('genre__rating', 'comdedy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre__rating', sa.Column('comdedy', sa.INTEGER(), nullable=True))
    op.drop_column('genre__rating', 'comedy')
    # ### end Alembic commands ###
